### ISSUE TITLE
Add transpilation related code to the repo

### ISSUE THREAD

**Issue by ramnivas** [j-funk/kissfft-js#1]
Would it be possible to add scripts/makefile etc that you use to get from C to js. Currently, there is the final product (the .js files), but not the way to recrated those.

**Comment by j-funk** [comment]
Will do tonight.

**Comment by j-funk** [comment]
@ramnivas done, let me know if there's anything else I can help with

**Comment by ramnivas** [comment]
Perfect! Thanks @j-funk
