### ISSUE TITLE
Fail to run fft test

### ISSUE THREAD

**Issue by tearsofphoenix** [j-funk/kissfft-js#2]
When run same test code, fftw-js works, kissfft-js fail with error like:
```
   RangeError: Maximum call stack size exceeded
      at ra (node_modules/kissfft-js/src/KissFFT.js:9:961)
      at ra (node_modules/kissfft-js/src/KissFFT.js:9:1393)
      at ra (node_modules/kissfft-js/src/KissFFT.js:9:1393)
```
Do you have any idea?
PS: run code on Mac OSX, NodeJS v8.6.0.

**Comment by j-funk** [comment]
What command are you using to run the test?

**Comment by tearsofphoenix** [comment]
1. Using: `mocha --require babel-core/register --reporter spec test/arithmetic-test.js`
2. Made extension on `Float64Array`:
```javascript
Float64Array.prototype.fft = function () {
  const n = this.length
  const fft = new FFTR(n)
  const transform = fft.forward(this)
  fft.dispose()
  return transform
}
```
3.test code:
```javascript
    const array = Float64Array.from(H0).fft()
    const real = array.real().round()
    assert.deepEqual(real, H0FFT_Real)
```
H0 is an array like: [1, 0, 0, 1..], it just fails at `const array = Float64Array.from(H0).fft()`
